inherit_from: .rubocop_todo.yml
require: rubocop-rspec
AllCops:
  UseCache: true
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
Documentation:
    Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false
Rails:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  # If `true`, this parameter means that single line method definitions don't
  # need an empty line between them.
  AllowAdjacentOneLineDefs: false
