- run: bash .circleci/setup-heroku.sh
- add_ssh_keys:
    fingerprints:
      - "c1:a5:98:bb:47:8c:02:7d:8a:07:f7:2f:ea:ac:b7:9b"
- deploy:
    name: Deploy Master to Heroku
    command: |
      if [ "${CIRCLE_BRANCH}" == "master" ]; then
        git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
        heroku run python manage.py deploy
        heroku restart
      fi